site_name: gtfs-skims
nav:
  - Home: index.md
  - Installation: installation.md
  - Running the tool: run.md
  - Methodology: methodology.md
  - Contributing: contributing.md
  - Changelog: CHANGELOG.md
  - Reference:
    - Command line interface: api/cli.md
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
repo_url: https://github.com/arup-group/gtfs_skims/
site_dir: .docs
markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
    alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
hooks:
  - docs/static/hooks.py
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: spacy
            show_bases: true
            filters:
              - "!^_"
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_signature_annotations: false
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://numpy.org/doc/stable/objects.inv

watch:
  - src/gtfs_skims

extra_css:
  - static/extras.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  version:
    provider: mike

extra_javascript:
  - static/extras.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js